language: objective-c
osx_image: xcode7

before_install:
  - "sudo xcode-select --install || true"
  - "brew install carthage"
  # Setup our vendored Roost
  - "cd vendor"
  - "git clone https://github.com/dirk/Roost.git"
  - "cd Roost"
  # Bootstrap and build Roost
  - "cd vendor && carthage bootstrap --platform mac --no-use-binaries"
  - "cd .. && make"
  # Get our own Carthage dependencies
  - "cd .. && carthage bootstrap --platform mac --no-use-binaries"
  # Return to the base directory
  - "cd .."

before_script: "vendor/Roost/bin/roost build"

script: "bin/index"
