language: objective-c
osx_image: beta-xcode6.3

before_install:
  - "sudo xcode-select --install || true"
  - "brew install carthage"
  - "brew install hub"
  - "git config --global hub.protocol https"
  # Setup our vendored Roost
  - "cd vendor"
  - "hub clone dirk/Roost"
  - "cd Roost"
  # Bootstrap and build Roost
  - "cd vendor && carthage bootstrap --platform mac"
  - "cd .. && make"
  # Get our own Carthage dependencies
  - "cd .. && carthage bootstrap --platform mac"
  # Return to the base directory
  - "cd .."

before_script: "vendor/Roost/bin/roost build"

script: "bin/roost.index"
